# Generated by Django 3.1.1 on 2020-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrating',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('3', 3), ('5', 5), ('7', 7), ('10', 10)]),
        ),
    ]
