# Generated by Django 3.1.1 on 2020-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201123_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('post_type', models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], default='IMAGE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='static/post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(to='posts.PostMaterial'),
        ),
    ]
