# Generated by Django 3.1.1 on 2020-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistpost',
            name='report',
            field=models.CharField(choices=[('SPAM', 'SPAM'), ('INAPPROPRIATE', 'INAPPROPRIATE')], default='SPAM', max_length=25),
        ),
    ]
