# Generated by Django 3.1.1 on 2020-12-03 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20201203_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
