# Generated by Django 3.1.1 on 2020-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201203_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmaterial',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
