# Generated by Django 3.1.1 on 2020-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201208_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
