# Generated by Django 3.1.1 on 2020-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201219_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_qr',
            field=models.FileField(blank=True, null=True, upload_to='static/post_qr_codes/'),
        ),
    ]
