# Generated by Django 3.1.1 on 2021-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20201230_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('post_url', 'Post URL'), ('story_url', 'Story URL'), ('audio', 'Audio')], default='text', max_length=10),
        ),
    ]
