# Generated by Django 3.1.1 on 2021-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_messagemodel_read_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='read_receipt',
            field=models.BooleanField(default=False),
        ),
    ]
