# Generated by Django 3.1.1 on 2020-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201222_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appname',
            old_name='name',
            new_name='host_name',
        ),
        migrations.AlterField(
            model_name='appname',
            name='type',
            field=models.CharField(choices=[('DEVELOPMENT', 'DEVELOPMENT'), ('PRODUCTION', 'PRODUCTION')], default='DEVELOPMENT', max_length=255, unique=True),
        ),
    ]
