# Generated by Django 3.1.1 on 2020-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('IMAGE', 'IMAGE')], default='IMAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='static/story_files'),
        ),
    ]
