# Generated by Django 3.1.1 on 2020-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
