# Generated by Django 3.1.1 on 2020-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_story_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
