# Generated by Django 3.1.1 on 2020-09-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_followuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='user',
            new_name='folowing',
        ),
    ]
