# Generated by Django 3.1.1 on 2020-09-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200910_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='follower',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='followuser',
            old_name='folowing',
            new_name='user',
        ),
    ]
