# Generated by Django 3.1.1 on 2020-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_websiteverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteverification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
