# Generated by Django 3.1.1 on 2020-12-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201219_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
