# Generated by Django 3.1.1 on 2020-12-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_qr',
            field=models.FileField(null=True, upload_to='static/user_qr_codes/'),
        ),
    ]
