# Generated by Django 3.1.1 on 2020-12-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201222_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_qr',
            field=models.FileField(blank=True, null=True, upload_to='static/user_qr_codes/'),
        ),
    ]
