# Generated by Django 3.1.1 on 2020-12-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_selectedcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_child_+', to='categories.Category'),
        ),
    ]
