# Generated by Django 3.1.1 on 2020-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention_comment', 'Mention Comment'), ('following', 'Following'), ('like_post', 'Like Post'), ('comment_post', 'Comment Post'), ('chat_started', 'Chat Started'), ('group_chat_add', 'Group Chat Add')], max_length=250),
        ),
    ]
