# Generated by Django 3.1.1 on 2020-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20201116_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention_comment', 'Mention Comment'), ('following', 'Following'), ('like_post', 'Like Post'), ('comment_post', 'Comment Post'), ('comment_reply', 'Comment_Reply'), ('rate_story', 'Rate Story'), ('rate_post', 'Rate Post'), ('chat_started', 'Chat Started'), ('group_chat_add', 'Group Chat Add')], max_length=250),
        ),
    ]
